name: streaming-bicep-whatif

on:
  pull_request:
    branches: [ main, collaborative ]   # include any branch you PR into
    paths:
      - 'infra/streaming-bicep/**'
      - '.github/workflows/streaming-bicep-whatif.yml'
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-nyctaxi-stream
  LOCATION: eastus2
  TEMPLATE_FILE: infra/streaming-bicep/main.bicep
  PARAM_FILE: infra/streaming-bicep/params.dev.json

concurrency:
  group: streaming-bicep-whatif-${{ github.ref }}
  cancel-in-progress: true

jobs:
  what-if:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # <-- required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


  
      - name: Who am I (debug)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account show -o table


      - name: Show effective template (debug)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az bicep install --upgrade
            az bicep version
            az deployment group validate \
              -g "$RESOURCE_GROUP" \
              -f "$TEMPLATE_FILE" \
              -p @"$PARAM_FILE" \
              --only-show-errors

      - name: Ensure RG exists
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create -n "$RESOURCE_GROUP" -l "$LOCATION"

      - name: Bicep What-If
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ${{ env.TEMPLATE_FILE }}
          parameters: ${{ env.PARAM_FILE }}
          additionalArguments: --what-if
          deploymentName: pr-whatif-${{ github.run_id }}
          failOnStdErr: false 
