name: streaming-bicep-whatif

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/streaming-bicep/**'
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-nyctaxi-stream
  LOCATION: eastus2
  TEMPLATE_FILE: infra/streaming-bicep/main.bicep
  PARAM_FILE: infra/streaming-bicep/params.dev.json

# Prevent overlapping What-If runs on the same PR
concurrency:
  group: streaming-bicep-whatif-${{ github.ref }}
  cancel-in-progress: true

jobs:
  what-if:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          # Use the same secret you use for Terraform
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure RG exists (no-op if present)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create -n "$RESOURCE_GROUP" -l "$LOCATION"

      - name: Bicep What-If
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ${{ env.TEMPLATE_FILE }}
          parameters: ${{ env.PARAM_FILE }}
          additionalArguments: --what-if
          # Use a stable deployment name per PR run
          deploymentName: pr-whatif-${{ github.run_id }}
