name: streaming-bicep-deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/streaming-bicep/**'
      - '.github/workflows/streaming-bicep-deploy.yml'
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-nyctaxi-stream
  LOCATION: eastus2
  TEMPLATE_FILE: infra/streaming-bicep/main.bicep
  PARAM_FILE: infra/streaming-bicep/params.dev.json

concurrency:
  group: streaming-bicep-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: streaming-dev   # ensure you have a matching OIDC federated credential for this env
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Who am I (debug)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account show -o table

      # Compile-only (avoid az deployment validate to prevent "response consumed")
      - name: Compile Bicep (debug)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -e
            az bicep install || true
            az bicep version
            az bicep build -f "$TEMPLATE_FILE" -o /tmp/main.json
            echo "Bicep compiled successfully."

      - name: Ensure RG exists
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create -n "$RESOURCE_GROUP" -l "$LOCATION"

      - name: Deploy Bicep (incremental)
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ${{ env.TEMPLATE_FILE }}
          parameters: ${{ env.PARAM_FILE }}
          deploymentName: stream-deploy-${{ github.run_id }}
          failOnStdErr: false   # ignore warning noise in stderr

      # Optional: show ASA job block to confirm sku in compiled JSON
      - name: Build Bicep to JSON & show ASA job
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -e
            az bicep install || true
            az bicep build -f "$TEMPLATE_FILE" -o /tmp/main.json
            echo "----- ASA job block (type, name, sku) -----"
            if command -v jq >/dev/null 2>&1; then
              cat /tmp/main.json | jq '.resources[] | select(.type=="Microsoft.StreamAnalytics/streamingjobs") | {type, name, sku: .sku}'
            else
              grep -nE '"Microsoft.StreamAnalytics/streamingjobs"|\"sku\"' /tmp/main.json || true
            fi
