name: streaming-bicep-deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/streaming-bicep/**'
      - '.github/workflows/streaming-bicep-deploy.yml'
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-nyctaxi-stream
  LOCATION: eastus2
  TEMPLATE_FILE: infra/streaming-bicep/main.bicep
  PARAM_FILE: infra/streaming-bicep/params.dev.json
  ASA_JOB_NAME: asa-nyctaxi-trip
  DATA_LOCALE: en-US
  LATE_SECONDS: 900
  COMPAT_LEVEL: "1.2"
  SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

concurrency:
  group: streaming-bicep-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: streaming-dev

    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Who am I (debug)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account show -o table

      - name: Ensure provider registered (Stream Analytics)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail
            az provider register -n Microsoft.StreamAnalytics -o none || true
            # Best-effort wait (usually quick; avoids random ARM 409s)
            for i in {1..20}; do
              state=$(az provider show -n Microsoft.StreamAnalytics --query registrationState -o tsv || echo "")
              echo "Microsoft.StreamAnalytics registrationState: ${state}"
              [ "$state" = "Registered" ] && break || sleep 3
            done

      - name: Ensure RG exists
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create -n "$RESOURCE_GROUP" -l "$LOCATION" -o none

      - name: Delete existing ASA job if present
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail
            if az resource show -g "$RESOURCE_GROUP" -n "$ASA_JOB_NAME" --resource-type Microsoft.StreamAnalytics/streamingjobs >/dev/null 2>&1; then
              echo "Existing ASA job found; deleting..."
              az resource delete -g "$RESOURCE_GROUP" -n "$ASA_JOB_NAME" --resource-type Microsoft.StreamAnalytics/streamingjobs
              for i in {1..30}; do
                if az resource show -g "$RESOURCE_GROUP" -n "$ASA_JOB_NAME" --resource-type Microsoft.StreamAnalytics/streamingjobs >/dev/null 2>&1; then
                  echo "Waiting for deletion... ($i)"; sleep 5
                else
                  echo "ASA job deleted."; break
                fi
              done
            else
              echo "No existing ASA job."
            fi

      - name: Create ASA job (robust API + SKU fallback)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail

            put_job () {
              local API="$1"      # e.g. 2021-10-01-preview or 2020-03-01
              local SHAPE="$2"    # "top" or "prop"
              local BODY="/tmp/asa-job.json"

              if [ "$SHAPE" = "top" ]; then
                cat > "$BODY" <<JSON
            {
              "location": "$LOCATION",
              "identity": { "type": "SystemAssigned" },
              "sku": { "name": "Standard" },
              "properties": {
                "jobType": "Cloud",
                "eventsOutOfOrderPolicy": "Adjust",
                "eventsOutOfOrderMaxDelayInSeconds": $LATE_SECONDS,
                "eventsLateArrivalMaxDelayInSeconds": $LATE_SECONDS,
                "dataLocale": "$DATA_LOCALE",
                "outputErrorPolicy": "Stop",
                "compatibilityLevel": "$COMPAT_LEVEL"
              }
            }
            JSON
              else
                cat > "$BODY" <<JSON
            {
              "location": "$LOCATION",
              "identity": { "type": "SystemAssigned" },
              "properties": {
                "sku": { "name": "Standard" },
                "jobType": "Cloud",
                "eventsOutOfOrderPolicy": "Adjust",
                "eventsOutOfOrderMaxDelayInSeconds": $LATE_SECONDS,
                "eventsLateArrivalMaxDelayInSeconds": $LATE_SECONDS,
                "dataLocale": "$DATA_LOCALE",
                "outputErrorPolicy": "Stop",
                "compatibilityLevel": "$COMPAT_LEVEL"
              }
            }
            JSON
              fi

              local URI="https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.StreamAnalytics/streamingjobs/$ASA_JOB_NAME?api-version=$API"
              az rest --method put --uri "$URI" --headers Content-Type=application/json --body @"$BODY" --only-show-errors -o none
            }

            echo "Creating ASA job $ASA_JOB_NAME ..."
            set +e
            put_job 2021-10-01-preview top; rc=$?
            if [ $rc -ne 0 ]; then
              echo "Fallback: 2020-03-01 with top-level sku"
              put_job 2020-03-01 top; rc=$?
            fi
            if [ $rc -ne 0 ]; then
              echo "Fallback: 2020-03-01 with properties.sku"
              put_job 2020-03-01 prop; rc=$?
            fi
            set -e
            if [ $rc -ne 0 ]; then
              echo "Failed to create ASA job after all attempts." >&2
              exit 1
            fi
            echo "ASA job created."

      - name: Wait for ASA managed identity (principalId)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail
            for i in {1..30}; do
              PID=$(az resource show \
                -g "$RESOURCE_GROUP" \
                -n "$ASA_JOB_NAME" \
                --resource-type Microsoft.StreamAnalytics/streamingjobs \
                --query "identity.principalId" -o tsv || true)
              if [ -n "$PID" ] && [ "$PID" != "None" ]; then
                echo "principalId ready: $PID"; break
              fi
              echo "Waiting for principalId... ($i)"; sleep 5
            done

      - name: Deploy Bicep (az cli)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail
            az deployment group create \
              --resource-group "$RESOURCE_GROUP" \
              --name "stream-deploy-${GITHUB_RUN_ID}" \
              --template-file "$TEMPLATE_FILE" \
              --parameters @"$PARAM_FILE" \
              --mode Incremental \
              --only-show-errors

      - name: Stop ASA job (cost-safe)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail
            # Try preview API, then stable API
            az rest --method post \
              --uri "https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.StreamAnalytics/streamingjobs/$ASA_JOB_NAME/stop?api-version=2021-10-01-preview" \
              -o none || az rest --method post \
              --uri "https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.StreamAnalytics/streamingjobs/$ASA_JOB_NAME/stop?api-version=2020-03-01" \
              -o none || true
