name: terraform-plan
on:
  pull_request:
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/terraform-*.yml'

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (remote backend)
        run: |
          terraform init \
            -backend-config="resource_group_name=platform-tfstate-rg" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_ACCOUNT }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=da/dev/infra.tfstate"

      - name: Terraform Fmt & Validate
        run: |
          terraform fmt -check -recursive
          terraform validate

      - name: Terraform Plan (Dev)
        env:
          TF_VAR_synapse_sql_admin_password: ${{ secrets.SYNAPSE_SQL_ADMIN_PASSWORD }}
        run: |
          terraform plan -input=false \
            -var-file=env/dev.tfvars \
            -var synapse_sql_admin_login="synadmin" \
            -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan
