name: terraform-apply-dev
on:
  push:
    branches: [ main ]
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/terraform-*.yml'
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (remote backend)
        env:
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform init \
            -backend-config="resource_group_name=platform-tfstate-rg" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_ACCOUNT }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=da/dev/infra.tfstate"

      - name: Terraform Apply (Dev)
        env:
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_synapse_sql_admin_password: ${{ secrets.SYNAPSE_SQL_ADMIN_PASSWORD }}
        run: |
          terraform apply -input=false \
            -var-file=env/dev.tfvars \
            -var synapse_sql_admin_login="synadmin" \
            -auto-approve
